steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/click-kaar/click-kaar:$SHORT_SHA
      - backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/click-kaar/click-kaar:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - click-kaar
      - --image
      - asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/click-kaar/click-kaar:$SHORT_SHA
      - --region
      - asia-south1
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 1Gi
      - --cpu
      - "1"
      - --set-env-vars
      - ^@^SPRING_PROFILES_ACTIVE=cloud@CORS_ALLOWED_ORIGINS=https://click-kaar.com,https://www.click-kaar.com,https://clickkaar.com,https://www.clickkaar.com,https://click-kaar.web.app,https://click-kaar.firebaseapp.com,http://localhost:4200,http://127.0.0.1:4200@FRONTEND_LOGIN_URL=https://click-kaar.web.app/login
      - --set-secrets
      - DB_URL=clickkaar-db-url:latest,DB_USERNAME=clickkaar-db-username:latest,DB_PASSWORD=clickkaar-db-password:latest,JWT_SECRET=clickkaar-jwt-secret:latest

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/click-kaar/click-kaar:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
